name: Build and Release JAR

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create bin directory
      run: mkdir -p bin
      
    - name: Compile Java classes
      run: javac -d bin src/**/*.java
      
    - name: Create JAR file
      run: |
        echo "Main-Class: Main" > manifest.txt
        cd bin
        jar cfm ../TaskManager.jar ../manifest.txt .
        cd ..
        
    # Add step to verify JAR contents
    - name: Verify JAR contents
      run: |
        echo "--- JAR Contents (root) ---"
        jar tf TaskManager.jar | grep -v / | sort
        echo "--- JAR Manifest --- "
        unzip -p TaskManager.jar META-INF/MANIFEST.MF

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: TaskManager.jar
        name: Task Manager ${{ github.ref_name }}
        body: |
          # Task Manager Release ${{ github.ref_name }}
          
          A simple task management application.
        
          ## Installation
          1. Make sure you have Java installed (JRE 8 or higher)
          2. Download the JAR file
          3. Double click on the JAR file or run with `java -jar TaskManager.jar`
          
        draft: false
        prerelease: false 