name: Build and Release JAR

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Compile Java classes
      run: javac -d build $(find src -name '*.java')
      
    - name: Create JAR file
      run: |
        echo "Main-Class: Main" > manifest.txt
        cd build
        # Create JAR from build directory contents
        jar cfm ../TaskManager.jar ../manifest.txt *
        cd ..
        
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: TaskManager.jar
        name: Task Manager ${{ github.ref_name }}
        body: |
          # Release ${{ github.ref_name }}
          
          A simple task management application.
        
          ## Installation
          1. Make sure you have Java installed (JRE 8 or higher) ([Download here](https://www.java.com/en/download/)).
          2. Download the `TaskManager.jar` file attached below.
          3. Double-click the JAR file to run it, OR open a terminal/command prompt in the location where you downloaded the JAR file and run `java -jar TaskManager.jar`.
          
        draft: false
        prerelease: false 